name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  backend-tests:
    name: Run Backend Unit & Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with coverage
        working-directory: backend
        run: pytest unit_tests/ -v --cov=app --cov-report=term-missing --cov-report=html

      - name: Run integration tests
        working-directory: backend
        run: pytest integration_tests/ -v

      - name: Check coverage threshold (95%)
        working-directory: backend
        run: pytest unit_tests/ integration_tests/ --cov=app --cov-report=term --cov-fail-under=95 --ignore=htmlcov

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/htmlcov/
          retention-days: 30

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/.pytest_cache/
          retention-days: 7
