name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_ENV: test
  CI: true

jobs:
  frontend-tests:
    name: Run Frontend Unit Tests (Jest)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Jest tests with coverage
        working-directory: frontend
        run: npm run test:coverage

      - name: Check coverage threshold (98%)
        working-directory: frontend
        run: |
          # Jest coverage configured in jest.config.mjs with 98% thresholds
          # This step will fail if coverage is below threshold
          npm run test:coverage -- --coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage/
          retention-days: 30

      - name: Upload lcov report for coverage analysis
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-lcov-report
          path: frontend/coverage/lcov.info
          retention-days: 30
